#!/bin/sh
# Usage:
#   dockertunnel user@remote docker ps

# extract machine
TARGET=${1}

# extract command
shift
set -- "$@"
COMMAND=$*

TMPID=$(uuidgen)
SOCK_FILE="/tmp/dockertunnel.${TMPID}.sock"
CTRL_FILE="/tmp/dockertunnel.${TMPID}.ctrl"

# setup target machine
unset DOCKER_TLS_VERIFY
export DOCKER_HOST="unix://${SOCK_FILE}"


# temporary socket tunnel
# https://stackoverflow.com/a/15198031/1793548
ssh -M -S "${CTRL_FILE}" -fnNT -L "${SOCK_FILE}:/var/run/docker.sock" -p 2377 "${TARGET}"

# run it
eval $COMMAND

# clean socket
ssh -S "${CTRL_FILE}" -O exit "${TARGET}"
rm "${SOCK_FILE}"
